version: '3.8'

services:
  # Backend API Service (Development)
  kemi-api:
    build:
      context: ./kemi-api
      dockerfile: Dockerfile
    container_name: kemi-api-dev
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - API_PORT=8000
      - NODE_ENV=development
      - DEBUG=true
    volumes:
      - ./kemi-api:/app
      - /app/__pycache__
    networks:
      - kemi-network
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend Service (Development)
  kemi-frontend:
    build:
      context: ./kemi-crypto
      dockerfile: Dockerfile.dev
    container_name: kemi-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_GEMINI_API_KEY=${GEMINI_API_KEY}
      - VITE_COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
    volumes:
      - ./kemi-crypto:/app
      - /app/node_modules
    depends_on:
      - kemi-api
    networks:
      - kemi-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: kemi-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kemi-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  kemi-network:
    driver: bridge

volumes:
  redis_data:
    driver: local