services:
  # Backend API service
  kemi-api:
    build:
      context: ./kemi-api
      dockerfile: Dockerfile
    container_name: kemi-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - PYTHONPATH=/app
    volumes:
      - ./kemi-api:/app
    networks:
      - kemi-network

  # Frontend service
  kemi-frontend:
    build:
      context: ./kemi-crypto
      dockerfile: Dockerfile
    container_name: kemi-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
    depends_on:
      - kemi-api
    networks:
      - kemi-network

networks:
  kemi-network:
    driver: bridge